--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/CooldownAPI
build-by-default: true
branches:
- main
projects:
  CooldownAPI:
    path: ""
    model: virion
    type: library
...
